version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kso_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_ADMIN: securepassword123
      POSTGRES_PASSWORD: secret_kso_password
      POSTGRES_DB: kso_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: